sudo: required
services:
  - docker

before_install:
  - docker build -t rsanto27/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rsanto27/react-test npm test -- --coverage

after_success:
  - docker build -t rsanto27/multi-client ./client
  - docker build -t rsanto27/multi-nginx ./nginx
  - docker build -t rsanto27/multi-server ./server
  - docker build -t rsanto27/multi-worker ./worker

  # Log in on dockerhub and push the images
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push rsanto27/mult-client
  - docker push rsanto27/mult-nginx
  - docker push rsanto27/mult-server
  - docker push rsanto27/mult-worker